version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily' # Check daily for security updates
      time: '09:00'
    open-pull-requests-limit: 15
    # Prioritize security updates
    allow:
      - dependency-type: 'all'
    groups:
      # Group security updates with high priority
      security-updates:
        patterns:
          - '*'
        update-types:
          - 'security'
      # Group Astro and related packages
      astro:
        patterns:
          - 'astro*'
          - '@astrojs/*'
        update-types:
          - 'minor'
          - 'patch'
      # Group dev dependencies
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      # Group production dependencies (minor and patch)
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
    labels:
      - 'dependencies'
      - 'automated'
    # Auto-approve security patches for known safe packages
    reviewers:
      - 'heridotlife'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    labels:
      - 'dependencies'
      - 'github-actions'
      - 'automated'
    commit-message:
      prefix: 'ci'
      include: 'scope'
