name = "astro-heridotlife"
compatibility_date = "2024-04-05"
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "D1_db"
database_name = "heridotlife"
database_id = "55bf671e-d7c3-43a2-ad26-0c3fa2a3d1da" # Get this from: wrangler d1 list

# Bind environment variables for Cloudflare Workers
# Add your actual values in Cloudflare Dashboard > Workers & Pages > Settings > Environment Variables
# These are just placeholders for local development with `wrangler pages dev`
[vars]
# Do not put real secrets here - use Cloudflare Dashboard for production
# AUTH_SECRET = "your-local-auth-secret"
# ADMIN_PASSWORD = "your-local-admin-password"