name = "heridotlife"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "heridotlife"
route = "heridotlife.com/*"

[env.staging]
name = "heridotlife-staging"
route = "staging.heridotlife.com/*"

[build]
command = "pnpm build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production.vars]
NEXT_PUBLIC_APP_URL = "https://heridotlife.com"
NEXT_PUBLIC_CLOUDFLARE_ANALYTICS_TOKEN = "YOUR_CLOUDFLARE_ANALYTICS_TOKEN"

[env.staging.vars]
NEXT_PUBLIC_APP_URL = "https://staging.heridotlife.com"
NEXT_PUBLIC_CLOUDFLARE_ANALYTICS_TOKEN = "YOUR_CLOUDFLARE_ANALYTICS_TOKEN" 