name = "astro-heridotlife"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "D1_db"
database_name = "heridotlife"
database_id = "55bf671e-d7c3-43a2-ad26-0c3fa2a3d1da"

# KV Namespace bindings
[[kv_namespaces]]
binding = "heridotlife_kv"
id = "65a1d9021c3142c0b9aaf6539c5a017d"

[[kv_namespaces]]
binding = "SESSION"
id = "65a1d9021c3142c0b9aaf6539c5a017d"

# Environment variables
[vars]
# Add your environment variables here
# Use Cloudflare Dashboard for production secrets