---
name: Security Vulnerability Report
description: Report a security vulnerability (use private reporting when possible)
title: '[SECURITY] '
labels: ['security', 'vulnerability']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report

        **Please use GitHub's private vulnerability reporting feature for security issues when possible.**

        If you need to report this publicly, please ensure you don't include sensitive details that could help attackers exploit the vulnerability.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe do you consider this vulnerability?
      options:
        - Critical
        - High
        - Medium
        - Low
      default: 0
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Affected Component
      description: Which part of the system is affected?
      placeholder: 'e.g., Authentication, API, Database, Frontend'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: 'Please provide a clear description of the vulnerability...'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the vulnerability
      placeholder: |
        1. Go to...
        2. Click on...
        3. Enter...
        4. Observe...
      value: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact
      description: What is the potential impact of this vulnerability?
      placeholder: 'Describe what an attacker could do if they exploit this vulnerability...'
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this issue?
      placeholder: 'Optional: Your suggestions for mitigating or fixing this vulnerability...'
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information
      placeholder: 'Environment details, references, etc...'
    validations:
      required: false

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure
      options:
        - label: I understand this is a public issue and will not include sensitive exploitation details
          required: true
        - label: I have attempted to contact the security team privately first (if applicable)
          required: false
